export enum EFeePaymentMethod {
  YAPE = 'YAPE',
  PLIN = 'PLIN',
  BCP = 'BCP',
  INTERBANK = 'INTERBANK',
  BBVA = 'BBVA',
  SCONTIABANK = 'SCOTIABANK',
  CASH_PAYMENT = 'EFECTIVO',
}

export const CFeePaymentMethod = {
  YAPE: 'YAPE',
  PLIN: 'PLIN',
  BCP: 'BCP',
  INTERBANK: 'INTERBANK',
  BBVA: 'BBVA',
  SCONTIABANK: 'SCOTIABANK',
  CASH_PAYMENT: 'EFECTIVO',
}

export enum EFeeStatus {
  PENDING = 'PENDIENTE',
  PROCESSING = 'PROCESANDO',
  REFUSED = 'RECHAZADO',
  PAID_OUT = 'PAGADO',
}

export const CFeeStatus = {
  PENDING: 'PENDIENTE',
  PROCESSING: 'PROCESANDO',
  REFUSED: 'RECHAZADO',
  PAID_OUT: 'PAGADO',
}
