export enum EProjectStatus {
  ALL = 'ALL',
  REQUIRED = 'SOLICITADO',
  ACCEPTED = 'ACEPTADO',
  REFUSED = 'RECHAZADO',
  PENDING = 'PENDIENTE',
  COMPLETED = 'COMPLETADO'
}

export const CProjectStatus = {
  REQUIRED: 'SOLICITADO',
  ACCEPTED: 'ACEPTADO',
  REFUSED: 'RECHAZADO',
  PENDING: 'PENDIENTE',
  COMPLETED: 'COMPLETADO',
}
